amqp-host: ${AMQP_HOST:localhost}
amqp-port: ${AMQP_PORT:5672}
amqp-username: ${AMQP_USERNAME:artemis}
amqp-password: ${AMQP_PASSWORD:artemis}
kafka:
  bootstrap:
    servers:
      - localhost:9092
quarkus:
  http:
    port: 8081
    test-port: 0
    test-ssl-port: 0
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_order}
    password: ${DB_PASSWORD:app_order}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost:15432}/${DB_DATABASE:app_order}
      max-size: 8
      min-size: 2
  jaeger:
    enabled: true
    endpoint: ${TRACING_ENDPOINT:http://localhost:14268/api/traces}
    sampler-type: const
    sampler-param: 1
    service-name: order-service
mp:
  messaging:
    incoming:
      jms-new-customer-channel:
        connector: smallrye-amqp
        durable: true
        use-anonymous-sender: false
    outgoing:
      kafka-new-order-channel:
        connector: smallrye-kafka
        topic: kafka-new-order-channel
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer