quarkus:
  http:
    port: 8081
    test-port: 0
    test-ssl-port: 0
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_order}
    password: ${DB_PASSWORD:app_order}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost:15432}/${DB_DATABASE:app_order}
      max-size: 8
      min-size: 2